name: media_plex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # service locator
  get_it: ^7.2.0
  # state management
  flutter_bloc: ^8.1.1
  # value equality
  equatable: ^2.0.5
  # functional programming thingies
  dartz: ^0.10.1
  # remote API
  http: ^0.13.5
  # cached image
  cached_network_image: ^3.2.3

  rxdart: ^0.27.7
  intl: ^0.18.0

  #local database
  sqflite: ^2.2.2


  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Fugaz
      fonts:
        - asset: assets/fonts/FugazOne-Regular.ttf