// import 'package:media_plex/media_plex/books/domain/entities/_created.dart';
// import 'package:media_plex/media_plex/books/domain/entities/author.dart';
// import 'package:media_plex/media_plex/books/domain/entities/_book_type.dart';
// import 'package:media_plex/media_plex/books/domain/entities/search.dart';
//
// BookDetails tBookDetails = BookDetails(
//   location: 'location',
//   key: 'key',
//   type: const BookType(key: 'key'),
//   latestRevision: 1,
//   revision: 1,
//   created: Created(
//     type: 'type',
//     value: DateTime.now(),
//   ),
//   lastModified: Created(
//     type: 'type',
//     value: DateTime.now(),
//   ),
// );
//
// Author tAuthor = Author(
//   wikipedia: 'wikipedia',
//   personalName: 'personalName',
//   key: 'key',
//   alternateNames: const ['alternateNames'],
//   remoteIds: const RemoteIds(
//     wikidata: 'wikidata',
//     isni: 'isni',
//     goodreads: 'goodreads',
//     viaf: 'viaf',
//     librarything: 'librarything',
//     amazon: 'amazon',
//   ),
//   type: const BookType(key: 'key'),
//   links: const [
//     Link(
//       title: 'title',
//       url: 'url',
//       type: BookType(key: 'key'),
//     ),
//   ],
//   name: 'name',
//   title: 'title',
//   birthDate: 'birthDate',
//   entityType: 'entityType',
//   photos: const [1, 2, 3],
//   sourceRecords: const ['sourceRecords'],
//   bio: 'bio',
//   latestRevision: 1,
//   revision: 1,
//   created: Created(
//     type: 'type',
//     value: DateTime.now(),
//   ),
//   lastModified: Created(
//     type: 'type',
//     value: DateTime.now(),
//   ),
// );
//
// Search tSearch = Search(
//   numFound: 1,
//   start: 1,
//   numFoundExact: false,
//   docs: [
//     Doc(
//       key: 'key',
//       type: BookType(key: 'key'),
//       seed: ['seed'],
//       title: 'title',
//       titleSuggest: 'titleSuggest',
//       editionCount: 1,
//       editionKey: ['editionKey'],
//       publishDate: ['publishDate'],
//       publishYear: [2022],
//       firstPublishYear: 2022,
//       numberOfPagesMedian: 1,
//       lccn: ['lccn'],
//       publishPlace: ['publishPlace'],
//       oclc: ['oclc'],
//       contributor: ['contributor'],
//       lcc: ['lcc'],
//       ddc: ['ddc'],
//       isbn: ['isbn'],
//       lastModifiedI: 1,
//       ebookCountI: 1,
//       ebookAccess: EbookAccess.BORROWABLE,
//       hasFulltext: false,
//       publicScanB: false,
//       ia: ['ia'],
//       iaCollection: ['iaCollection'],
//       iaCollectionS: 'iaCollectionS',
//       lendingEditionS: 'lendingEditionS',
//       lendingIdentifierS: 'lendingIdentifierS',
//       printdisabledS: 'printdisabledS',
//       coverEditionKey: 'coverEditionKey',
//       coverI: 1,
//       publisher: ['publisher'],
//       language: ['language'],
//       authorKey: ['authorKey'],
//       authorName: ['authorName'],
//       authorAlternativeName: ['authorAlternativeName'],
//       person: ['person'],
//       place: ['place'],
//       subject: ['subject'],
//       time: ['time'],
//       idAlibrisId: ['idAlibrisId'],
//       idAmazon: ['idAmazon'],
//       idBetterWorldBooks: ['idBetterWorldBooks'],
//       idCanadianNationalLibraryArchive: ['idCanadianNationalLibraryArchive'],
//       idDepsitoLegal: ['idDepsitoLegal'],
//       idGoodreads: ['idGoodreads'],
//       idGoogle: ['idGoogle'],
//       idLibrarything: ['idLibrarything'],
//       idOverdrive: ['idOverdrive'],
//       idPaperbackSwap: ['idPaperbackSwap'],
//       idWikidata: ['idWikidata'],
//       iaLoadedId: ['iaLoadedId'],
//       iaBoxId: ['iaBoxId'],
//       publisherFacet: ['publisherFacet'],
//       personKey: ['personKey'],
//       placeKey: ['placeKey'],
//       timeFacet: ['timeFacet'],
//       personFacet: ['personFacet'],
//       subjectFacet: ['subjectFacet'],
//       version: 1.0,
//       placeFacet: ['placeFacet'],
//       lccSort: 'lccSort',
//       authorFacet: ['authorFacet'],
//       subjectKey: ['subjectKey'],
//       ddcSort: 'ddcSort',
//       timeKey: ['timeKey'],
//       firstSentence: ['firstSentence'],
//       subtitle: 'subtitle',
//       idBcid: ['idBcid'],
//     ),
//   ],
//   searchNumFound: 1,
//   q: 'q',
//   offset: 'offset',
// );
